### ISSUE TITLE
Story #3993: AI classification not shown in mod dashboard?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#101]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/
**user:** moderator

I made many offensive comments which were also classified as offensive, but at least not all appear on the tile of the moderations dashboard. I am not really sure if this is part of this story, in the acceptance criteria was the following:

"if the answer of the AI is ‘offensive’, this is stored as a classification of the comment (see also comment here https://taiga.liqd.net/project/mkay-kosmo/us/26?no-milestone=1) ) **and thus shown in the moderator dashboard**"

Dunno if that is rather relevant for the moderations tab story? Or does it belong here?

<img width="966" alt="Bildschirmfoto 2021-04-14 um 11 22 15" src="https://user-images.githubusercontent.com/30862422/114687842-6d160b00-9d14-11eb-99cb-aa07a2614360.png">

**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
Yes, currently we are only showing the number of reported comments there, so not the AI classifications as this was not ready when the tile was implemented. I would move the issue to story #4021 as we have to think about how we do it there anyway.
