### ISSUE TITLE
Mod Tab: Indicate if project is over

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#102]
**URL:** https://kosmo-dev.liqd.net/liqd/projects/debate-debate/
**user:** moderator
**expected behaviour:** tile in the moderations dashboard indicates that project is over
**behaviour:** tile does not display information

**important screensize:** 
**device & browser:** firefox 87.0 (64-Bit), MacOS BigSur

**Comment/Question:** Did we plan that in the design, @mcastro-lqd ? I am not sure if we planned it at all, but it is in the acceptance criteria (and I think it is useful). And future project as well as ongoing participation is indicated! Yay!!

<img width="1038" alt="Bildschirmfoto 2021-04-14 um 11 50 54" src="https://user-images.githubusercontent.com/30862422/114691216-b7e55200-9d17-11eb-89ae-f99914f9ffbd.png">

**Comment by phillimorland** [comment]
@hmkay future projects start dates are displayed but there was no design for finished project tiles so nothing was added, what wording would you like?

**Comment by mcastro-lqd** [comment]
@hmkay @phillimorland I thought it would be displayed something like in the organisation page like, "Beendet" or "Abgeschlossen" Would that be enough?

**Comment by phillimorland** [comment]
Sure, @hmkay fine by you?

**Comment by hmkay** [comment]
@mcastro-lqd @phillimorland sounds great!
