### ISSUE TITLE
sorting moderation tab: ones with comments first

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#103]
**URL:** Moderation Dashboard
**user:** moderator
**expected behaviour:** The projects with the most reported comments are shown first, the newest ones are after current / running projects and older projects
**behaviour:** upcoming projects are first on the list 

**Comment/Question:** I think we forgot about the upcoming projects and where to put them. This is not an important issue and as we will be talking about the sorting and filtering, maybe not necessary to put it into this current milestone? What do you think?

<img width="979" alt="Bildschirmfoto 2021-04-14 um 15 47 40" src="https://user-images.githubusercontent.com/30862422/114720999-c98b2180-9d38-11eb-8d56-8f13b342de9b.png">

**Comment by Rineee** [comment]
Isnt this rather a story? I remember vaguely that we wanted to do the sorting and filtering in its own story or was that just for the displaying of comments?

**Comment by phillimorland** [comment]
There was no acceptance criteria for ordering so this would be another story. Theres some basic ordering for the comment list which I've already started looking at but not for this view.

**Comment by hmkay** [comment]
I will add it to that story!
