### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#104]
**URL:** Moderation Tab
**user:** Moderator
**behaviour:** There is "Tage" written, even though the rest is in English

**Comment/Question:** to keep in mind,...

<img width="979" alt="Bildschirmfoto 2021-04-14 um 15 47 40" src="https://user-images.githubusercontent.com/30862422/114721430-34d4f380-9d39-11eb-9858-5baea5139635.png">

**Comment by phillimorland** [comment]
@hmkay, as we don't do any of the translations becasue PM and translators do them in transifix now i'm not sure if we should leave this in github? 
only english wording issues are code issues

**Comment by fuzzylogic2000** [comment]
This was because the translation came from another package. With our own translations everything will be translated
