### ISSUE TITLE
#3816 [KOSMO] no reference to reported comments in the Project Tile in Modarator Tab

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#105]
URL: https://kosmo-dev.liqd.net/userdashboard/moderation/
user: admin/ cms-editors/ developers
expected behaviour: project tile indicates no of outstanding reported comments
behaviour: number of outstanding comments are not shown in project tile (I wrote 
important screensize: desktop
device & browser: Desktop, firefox 87.0 (64-Bit)*
Comment/Question: hello, I do not know if this has already been reported in issue #101 but in my tiles the comments that should be reported are not displayed. I attach an image of the problem. 

[Screenshot 2021-04-14 at 15.48.00.pdf](https://github.com/liqd/a4-kosmo/files/6311286/Screenshot.2021-04-14.at.15.48.00.pdf)

**Comment by phillimorland** [comment]
@rilanari did you mark them as reported? I don't think the AI reported comments are included in there yet, are they @Rineee?

**Comment by Rineee** [comment]
No, only user reported comments are shown there so far.

**Comment by rilanari** [comment]
Oh thanks Rine! now I see that if a participant reports the comment it shows on the tile! should we close this issue?
