### ISSUE TITLE
adapt styling: Mails have different languages in footer

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#107]
**user:** moderation
**expected behaviour:** Mails have one language
**behaviour:** there is German and English - did I miss translating something? Is that in wagtail?

<img width="644" alt="Bildschirmfoto 2021-04-14 um 16 29 14" src="https://user-images.githubusercontent.com/30862422/114728145-1e319b00-9d3f-11eb-955b-7d340a36d30c.png">

**Comment by phillimorland** [comment]
note: need to change the template so platform name is not included in traslation so we don't need to redo translation for each new name

**Comment by phillimorland** [comment]
this is translation that wasn't translated yet for kosmo or a+

**Comment by hmkay** [comment]
Hey @phillimorland ,
thanks! I made a new milestone for the port to aplus and put it in there!

**Comment by fuzzylogic2000** [comment]
Translation will come from a+ with the next rebase
