### ISSUE TITLE
wording to check in userdashboard/assets/js

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#116]
semiprivate should be semipublic:
https://github.com/liqd/a4-kosmo/blob/37d506683de79dacc3dc0be5068102a508e26bbf/apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationProjects.jsx#L75

These text-bits were hard to translate and might not work - to check later:
https://github.com/liqd/a4-kosmo/blob/37d506683de79dacc3dc0be5068102a508e26bbf/apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationComment.jsx#L32

**Comment by Rineee** [comment]
Hm, this is tricky. For example we have this string
https://github.com/liqd/a4-kosmo/blob/df46b68474225bffad71f1eaf137936be7ed84c2/apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationComment.jsx#L8
which is used here
https://github.com/liqd/a4-kosmo/blob/df46b68474225bffad71f1eaf137936be7ed84c2/apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationComment.jsx#L33

To translate into german, we could either have a second string 
`const offensiveTextReport2 = django.pgettext('kosmo', '')`
that is empty in english, but could be filled with the second part of the german sentence in translations. 

Or we could pass the whole translated string through context?

What do you think @fuzzylogic2000 ?

**Comment by fuzzylogic2000** [comment]
Oh! I think, the text-bits are not yet really solved, so will reopen...
I think, it's good idea to add the string to translate to the context? We need it with variables, otherwise, we will have the translation problem again in every language, because its not translatable for translators, but only for devs.
The translation docs say, that it's not really doable in js: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#internationalization-in-javascript-code Or we could try the interpolate?

**Comment by fuzzylogic2000** [comment]
@Rineee That was meant as answer for you, but I forgot to tag you. :)

**Comment by fuzzylogic2000** [comment]
Ahhh, shouldn't have reopenened, is a duplicate. :p
But I just had the idea of a third option @Rineee :
We could also add different strings and show them depending on the variables. So, 
```
if AI true: display string_1
else: display string_2
```

**Comment by Rineee** [comment]
@fuzzylogic2000 Yes, but we would also need ifs for every value the variable 'classification' can take.. and we would have to hard code it instead of just taking the value of it.. so I think I would prefer trying it with the context, what do you think?

**Comment by fuzzylogic2000** [comment]
@Rineee Yes, true, that's better!
I didn't check what we put in there...
