### ISSUE TITLE
Landing page mobile

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#119]
**URL:** kosmo-dev.liqd.net
**user:** participant
**expected behaviour:** Design is clean / adaptive
**behaviour:** I cannot log in because the links are not accessible
**important screensize:** mobile
**device & browser:** Iphone SE 2020, Safari

**Comment/Question:** Not sure how much we checked mobile. @mcastro-lqd or @rilanari  did you?

![IMG_DCE9AE4FC041-1](https://user-images.githubusercontent.com/30862422/116059258-f0265200-a680-11eb-9f85-ef529ac7e186.jpeg)

**Comment by hmkay** [comment]
Depending on how easy this is, I would either put it into the next Milestone or then the Milestone which will be the next deployment somewhere in Sept / Oct / Nov. @phillimorland Is this an easy fix?

**Comment by phillimorland** [comment]
@hmkay this would actually be a design story, the hero header was built for a+ and only ever meant to be 2-3 words and sub header wasn't meant to be many more, we should have added a char limit but didn't as we were going to be the ones editing it so thought limiting didn't matter but I guess when it breaks the design we should always do it

**Comment by fuzzylogic2000** [comment]
@phillimorland I think, we should just limit the chars in a+, then! So, we will port it over next time we rebase. (https://github.com/liqd/adhocracy-plus/issues/1233)
@hmkay For now, please use less words. Otherwise they will be cut off with the next a+-rebase anyway. :p

**Comment by hmkay** [comment]
Sounds good, will do =) Thanks @phillimorland and @fuzzylogic2000 !
