### ISSUE TITLE
Browser says I haven´t sent information

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#120]
**URL:** https://kosmo-dev.liqd.net/liqd/subjects/2021-00017/
**user:** admin
**expected behaviour:** I reported a comment and then just go via the "back" button back to the discussion
**behaviour:** My browser warns me that I haven´t sent the information that I put in - but I did!
**important screensize:** Desktop
**device & browser:** MacBook, Mozilla
**Comment/Question:** Is this something in our hands or is it something with the Browser I use?

<img width="935" alt="Bildschirmfoto 2021-04-26 um 11 30 02" src="https://user-images.githubusercontent.com/30862422/116061378-12b96a80-a683-11eb-99e2-64248c54b7ec.png">

**Comment by hmkay** [comment]
> No, I think we should fix that.. but it is a problem that was there before with the reports, could you maybe rather open an issue in Aplus, so we fix it there and then port it over to Kosmo? Thank you!!

Done! It is here now: https://github.com/liqd/adhocracy-plus/issues/1226#issue-867514280

I did not add any tags, labels, etc, maybe you could do that @Rineee ?

**Comment by Rineee** [comment]
Thank you! I will do that.
