### ISSUE TITLE
Mod Dashboard: links of users lead to landing page

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#122]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/debate-debate/
**user:** moderation
**expected behaviour:** When I click on the hyperlink of the user name I am brought to the profile of the user
**behaviour:** hyperlink leads to landing page
**important screensize:** dektop

<img width="775" alt="Bildschirmfoto 2021-04-26 um 11 37 44" src="https://user-images.githubusercontent.com/30862422/116062874-9cb60300-a684-11eb-978f-6728c2ad78db.png">

**Comment by Rineee** [comment]
Oh yes, thats a left over .. but should we really link to the profile or just delete the link (thats how its meant to be in the designs, I think)?

**Comment by hmkay** [comment]
Maybe for now we could just add the link - as a moderator this is a nice chance to see if that person did some more weird stuff in other projects.
