### ISSUE TITLE
Mod Dashboard: Language mix

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#123]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/debate-debate/
**user:** moderation
**expected behaviour:** Moderation Dashboard is in one language
**behaviour:** There seems to be a mix of languages in the mod dashboard, did I forget to translate some strings?

<img width="775" alt="Bildschirmfoto 2021-04-26 um 11 44 54" src="https://user-images.githubusercontent.com/30862422/116063293-1948e180-a685-11eb-899c-a9c3b317cc90.png">

**Comment by Rineee** [comment]
Hahaa, that is a nice mixture :rofl: No, its because these are partly new strings, that werent there when you translated.. how did you do it with the translations, did Katharina just send you the po file and you sent it back?

**Comment by hmkay** [comment]
> Hahaa, that is a nice mixture 🤣 No, its because these are partly new strings, that werent there when you translated.. how did you do it with the translations, did Katharina just send you the po file and you sent it back?

It is the perfect Denglish :D 
Yes, exactly, @fuzzylogic2000 just sent me the po file. So you are happily invited to do the same @Rineee =)

**Comment by fuzzylogic2000** [comment]
fixed in #125
