### ISSUE TITLE
Error in Netiquette Page in dev and stage 

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#128]
**URL:** https://kosmo-dev.liqd.net/use-case-test-organisation/netiquette/
**user:** *moderator/ initiator/ participants
**expected behaviour:** the page should show the nettiquette
**behaviour:** in dev and stage platforms are leading to error 404
**important screensize:** desktop
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)*
**Comment/Question:** Hi! I configured every "important page" in Wagtail but the Netiquette does not work. :(
![Screenshot 2021-05-18 at 11 27 22](https://user-images.githubusercontent.com/77740788/118629178-a20ef500-b7cd-11eb-8807-659e7b93ef4e.png)

**Comment by fuzzylogic2000** [comment]
I have no idea. But it doesn't have to do with the important pages as when you click on "view live" in the wagtail dashboard, the page also isn't found.
I added another netiqutte and added that to the settings and that is fine. :thinking:

**Comment by rilanari** [comment]
Hallo Katharina, ok, I changed the name of the netiquette's page and now it works. hmm... so in stage the page is New Netiquette...
