### ISSUE TITLE
KOSMO in other lenguages

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#129]
**URL:** https://kosmo.liqd.net/userdashboard/overview/
**user:** *moderator/ initiator/ admin/ *
**expected behaviour:** I expect to see every text in the same language when I change to Dutch, Russian...
**behaviour:** Instead I see some text in English and some in Dutch / Russian/ etc
**important screensize:** Desktop
**device & browser:** Desktop, firefox 68.0.2 (64-Bit)
**Comment/Question:** *Is this easy to fix? is this necessary to change? 

 
![Screenshot 2021-06-08 at 15 29 45](https://user-images.githubusercontent.com/77740788/121196568-e4799e00-c870-11eb-8c58-a9fa976aeae3.png)

**Comment by phillimorland** [comment]
@rilanari do you have translators for these languages in KOSMO?

**Comment by phillimorland** [comment]
@rilanari as there is no one to translate KOSMO into these languages then only the wording from a+ will be translated, any strings added specifically for KOSMO will not be translated
