### ISSUE TITLE
AI repots comment repeated ammount of times in Moderation's Dashboard

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#132]
https://kosmo.liqd.net/praxis-tests/subjects/2021-00084/?comment=2013

User: Moderator

I would expect to see the comment to moderate only once in the moderation dashboard

The comment appears several in the moderation dashboard as reported by the AI

web browser: firefox 9.1.0 (64-Bit)

Could it be that the AI sees different things in the comment and therefore it reports it many times? 
How would it work if at one point the AI can identify other categories, like "good comment"? 

![Screenshot 2021-08-18 at 13 57 46](https://user-images.githubusercontent.com/77740788/129897324-246dab31-d307-4288-b347-2a798ad6271b.png)

**Comment by phillimorland** [comment]
@rilanari is this still occurring?

**Comment by rilanari** [comment]
it seems it's not happening anymore!!! yayyy

**Comment by Rineee** [comment]
@rilanari Just for explanation: We send the comment to the AI every time it is changed. Problem was that also by blocking a comment it is technically changed and thus sent to the AI again, resulting in another notification. So you can actually create new notifications (for the same comment) by blocking the comment :sweat_smile: It is still like this on dev, but we are fixing this behaviour at the moment!

**Comment by rilanari** [comment]
oh thanks @Rineee for the clarification!!!
