### ISSUE TITLE
Moderation Dashboard: many notifications for the same comment apear in the MD 

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#134]
URL: https://kosmo.liqd.net/userdashboard/moderation/detail/ki-in-online-diskussionen/

user: moderator

expected behaviour: if many participants and AI report a comment, I would like to see it only once in the Moderation Dashboard. 

behaviour: now it appears many times

device & browser: Desktop, firefox 68.0.2 (64-Bit)*

Comment/Question: would it be possible to display in the comment how many times the same comment has been reported? Also is it possible to see in the moderation dashboard the reasons that people give when they report that comment? 

![Screenshot 2021-08-18 at 15 13 43](https://user-images.githubusercontent.com/77740788/129904991-250956c8-5675-4879-9eb2-39e9bd597266.png)

**Comment by rilanari** [comment]
![Screenshot 2022-03-02 at 16 06 18](https://user-images.githubusercontent.com/77740788/156388418-313c3bc3-e26f-48ae-bc14-e811ea28f585.png)

**Comment by phillimorland** [comment]
I believe this is behaviour we are not planninf to change, @fuzzylogic2000 @Rineee that's correct right?

**Comment by fuzzylogic2000** [comment]
Yes! @Rineee is currently fixing it in a4 and we will cluster all notifications for the same comment anyway.
