### ISSUE TITLE
Moderation Dashboard: Filtering (All, Pending, Archived) not immediate!

### ISSUE THREAD

**Issue by khamui** [liqd/a4-kosmo#147]
**URL:** local/dev
**user:** moderator
**expected behaviour:** Changing filter from "All" to "Pending" or "Archived" showing immediately the right content
**behaviour:**  Changing leads to -sometimes- showing wrong notifications. Being corrected after 1-2 seconds.
**important screensize:** any
**device & browser:** tested in chrome
**Comment/Question:** It filters correctly, but there is a glitch of ~1 sec. where it can show wrong notifications.

Screenshot?

**Comment by phillimorland** [comment]
@khamui is this to do with the constant polling? maybe we need to force a fetch on filter choice instead of wait for the polling fetch? does that even make sense?

**Comment by khamui** [comment]
oh true, that would make sense!
