### ISSUE TITLE
Moderation Dashboard – Organization List 1

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#153]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/
**important screensize:** *Desktop*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *If possible, the Organizations List should be display as a list, not side by side.* 

<img width="360" alt="Screenshot 2021-11-16 at 09 22 20" src="https://user-images.githubusercontent.com/59610786/141947756-c4c2ee61-ccf4-4042-a2ed-2a40b2c90ab3.png">

**Comment by phillimorland** [comment]
fixed in https://github.com/liqd/a4-kosmo/pull/301
