### ISSUE TITLE
Moderation Dashboard – Comment Notification Tile – Action is a bit off

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#154]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**important screensize:** *Mobile*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:**Would it be possible to change this on Mobile? Like, Instead of putting the action between the profile pic and the 3 Dots Icon, leave them below** 

Currently: 
![Screenshot 2021-11-16 at 09 36 57](https://user-images.githubusercontent.com/59610786/141951381-5118a03b-1920-488e-84e2-4f019acb1fc4.png)

How it could be: 
![Screenshot 2021-11-16 at 09 36 10](https://user-images.githubusercontent.com/59610786/141951424-c056a1b5-df80-4244-9d13-62dd00b4e903.png)

**Comment by rilanari** [comment]
Hello @mcastro-lqd, could you please quickly check if this is fixed? Vilen Dank!!! :)

**Comment by mcastro-lqd** [comment]
@rilanari 

That's the current state: 
![IMG_5291](https://user-images.githubusercontent.com/59610786/183668005-c1d88d9b-b1e5-4c20-a126-3163f488de39.jpg)
