### ISSUE TITLE
Moderation Dashboard – Project Tag

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#155]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**important screensize:** *Desktop*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *The Tag here seems a bit off, if possible, it should be more closer to the title than the buttons* 

<img width="1019" alt="Screenshot 2021-11-16 at 09 26 32" src="https://user-images.githubusercontent.com/59610786/141952425-e0c40991-c224-4d68-9651-fce54a520871.png">

**Comment by phillimorland** [comment]
@mcastro-lqd do you mean the dot? I think that indicates that there are new notifications but it should be bigger like in designs unless you are talking about something else?

**Comment by mcastro-lqd** [comment]
@phillimorland No, I mean the Tag **( Public )**
