### ISSUE TITLE
Moderation Dashboard – Tab 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#156]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/
**important screensize:** *Both*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *There is a thin blue line here* 

Desktop:
<img width="205" alt="Screenshot 2021-11-16 at 10 26 53" src="https://user-images.githubusercontent.com/59610786/141959239-8c24bf4c-ab0a-4f1c-ba0d-72a99a860a3d.png">

Mobile:
![IMG_7689](https://user-images.githubusercontent.com/59610786/141959101-59c28a18-6e0e-425a-91c9-774550b4f0f5.jpg)

**Comment by khamui** [comment]
I checked today and i am not sure if this has been resolved in the meantime? @mcastro-lqd can you please check again if this still happens?

**Comment by mcastro-lqd** [comment]
@khamui no, not anymore

**Comment by khamui** [comment]
alright, thanks for checking!

**Comment by khamui** [comment]
@mcastro-lqd @phillimorland double checked and it does not appear anymore. so not an issue
