### ISSUE TITLE
Moderation Dashboard – Tab (Mobile) 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#157]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/
**important screensize:** *Mobile*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *Is it possible to center the text + arrow here on Mobile and increase the padding on the sides? * 

Currently:
![IMG_7689](https://user-images.githubusercontent.com/59610786/141959971-da442959-2440-49e3-9510-64f7b43a2d50.jpg)

How it could be: 
![Screenshot 2021-11-16 at 10 36 25](https://user-images.githubusercontent.com/59610786/141960154-f6436d47-98c9-4920-8a5f-25f3bf8fd4a9.png)

**Comment by phillimorland** [comment]
to be fixed in aplus
