### ISSUE TITLE
Moderation Dashboard – Notification Tile

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#159]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**important screensize:** *Desktop*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612*
**Comment/Question:** *Is it possible to increase the padding a bit on the notification tiles? Currently we have approximately 16 pixels I guess (?) but it would be good to have a bit more, like that:*

![Screenshot 2021-11-16 at 11 01 01](https://user-images.githubusercontent.com/59610786/141964492-5986c614-fefb-43a2-a86e-e3a57b81fb42.png)

**Comment by phillimorland** [comment]
seems to be fixed
