### ISSUE TITLE
Moderation Dashboard – Notification Tile Hover

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#160]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**important screensize:** *Both*
**device & browser:** *Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *I can't find any design proposals using the hover drop shadow for the Notification Tile. The only reccomended thing here was the grey-hover on the buttons like we have on the comments*

Comments: 
<img width="971" alt="Screenshot 2021-11-16 at 11 08 31" src="https://user-images.githubusercontent.com/59610786/141966267-4b759cef-eaa4-45f1-bc3e-593be53e261d.png">

Design:
![Screenshot 2021-11-16 at 11 14 17](https://user-images.githubusercontent.com/59610786/141966438-10dac665-af39-40d1-bf31-ae45e67e0f64.png)

**Comment by phillimorland** [comment]
@mcastro-lqd i'm a bit confused about what you what you would like us to do here? we have default styling for dropdown's which we use everywhere, would you like that changed?

**Comment by phillimorland** [comment]
Ahhh @mcastro-lqd is that this one? https://github.com/liqd/a4-kosmo/issues/190

**Comment by mcastro-lqd** [comment]
@phillimorland yes
