### ISSUE TITLE
Moderation Dashboard – Warning Message

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#161]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**important screensize:** *Mobile & Desktop*
**device & browser:** *Safari Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *Is it easy to put the warning message where the tile is? Cause currently if we have a long tile list, the message is displayed on top and the user can't see it if you don't scroll back to the top. I think it would make more sense if its displayed where the action took place, right?* 

Currently: 
<img width="842" alt="Screenshot 2021-11-16 at 11 18 26" src="https://user-images.githubusercontent.com/59610786/141967694-cc8a5435-922a-4516-a446-dcc123942151.png">

How it could be:
![Screenshot 2021-11-16 at 11 18 47](https://user-images.githubusercontent.com/59610786/141967727-cfd02389-edbc-496b-a16b-be76207be50d.png)

**Comment by khamui** [comment]
currently for statement actions (adding/editing/deleting) we show near tile. Changing this for notification actions (blocking, archiving etc.) shouldn't be too much of work @mcastro-lqd
