### ISSUE TITLE
Note from blocked and archived comments in MD describe it as spam

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#163]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/deliberation-on-how-to-use-ai-in-discussions/
**user:** Moderator
**behaviour:** The notification of blocked comments says that it was blocked because it is a spam, but this is not always true
**important screensize:** Web browser
**device & browser:**  Firefox 93.0 (64-bit)
**Comment/Question:**  Hello devs! Why does it say blocked because it is spam? was it agreed to show a reason in the Moderation Dashboard why it was blocked? I would not put also that it is negative.

<img width="1017" alt="Screenshot 2021-11-16 at 14 15 41" src="https://user-images.githubusercontent.com/77740788/141994030-ea9aba11-7542-4de2-8bd7-16b6df1e34a6.png">

**Comment by fuzzylogic2000** [comment]
It is in the designs like that. We can discuss and change it, though. But not connected to the story. :)

**Comment by Rineee** [comment]
@rilanari Would you like to change the wording here? If yes, to what? Maybe just 'This comment was blocked.'?

**Comment by rilanari** [comment]
Hello @Rineee, yes, it should only say 'This comment was blocked'

Thanks
