### ISSUE TITLE
Notes are in German and English

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#164]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/deliberation-on-how-to-use-ai-in-discussions/
**user:** Moderator
**expected behaviour:** The notes, that show if a comment was blocked, are all in English
**behaviour:** Those notes respect the language that is set
**important screensize:**
**device & browser:** Web browser
**Comment/Question:** Hello devs. I do not know if this is ok or not, or it will be arranged later, but the added notes are not consistent to language. This happens in the MD as well as in the discussion. 

Discussion:

<img width="888" alt="Screenshot 2021-11-16 at 14 43 37" src="https://user-images.githubusercontent.com/77740788/141996385-ae6b3df4-4e55-4717-814b-0b40683cb049.png">

Moderation Dashboard:

<img width="1017" alt="Screenshot 2021-11-16 at 14 15 41" src="https://user-images.githubusercontent.com/77740788/141996721-a4ffe9d7-dd81-41fc-b371-d880486b8572.png">

**Comment by fuzzylogic2000** [comment]
yes, we did not yet add translations. 
And note to devs: did we mark these strings as kosmo-strings, so that we can find them in the translation files?
