### ISSUE TITLE
Alert for blocked comments wrong

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#165]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** When I block a comment in the moderators dashboard, the alert says, that I blocked the notification. (see screenshot)
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Screenshot from 2021-11-26 16-18-28](https://user-images.githubusercontent.com/8178179/143601918-739b89d0-eb85-428d-9315-f7903df8ca16.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 not sure I get it, it seems to be saying the right thing? @rilanari do you want it to say something specific?

**Comment by fuzzylogic2000** [comment]
@phillimorland It should say that the comment was blocked, not the notification.

**Comment by rilanari** [comment]
hello @phillimorland ! exactly! the comment was blocked, not the notification! Could you change it to "Comment blocked successfully " ?
