### ISSUE TITLE
blocked comments look different from deleted comments

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#166]
**URL:** https://kosmo-dev.liqd.net/liqd/ideas/2021-00020/?comment=49
**user:** 
**expected behaviour:** To be discussed, preferably here in this issue. :)
**behaviour:** While for deleted comments, user name, user image, rating and rates, sharing, reporting, and actions in dropdown are not shown, we do show all of these for the blocked comments. Currently, the only thing we change is not showing the text for the blocked comments.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Screenshot from 2021-11-26 16-22-16](https://user-images.githubusercontent.com/8178179/143602289-b0b39936-ffe0-469d-9ac4-433c37d54124.png)

**Comment by fuzzylogic2000** [comment]
In my opinion the blocked comment should behave and look like the deleted comment. 
We could still show the delete-button in the dropdown to enable users to delete their comment even after it was blocked. But that does not make sense, when we do not show the username (and image)?
Anyway, let's discuss! What do you think @hmkay @rilanari @mcastro-lqd ?

**Comment by hmkay** [comment]
Thanks, @fuzzylogic2000 !
Yes, I also think they should behave and look the same! That would be good! Also, because we only call it "blocked" in order to be able to "undelete" it in case we need to do that. So how can we make them similar? Probably @mcastro-lqd has an idea for that? ;)
All he best!

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @hmkay I actually always thought they would look like the deleted comments, I don't see the point of showing the username + picture. They can be called blocked ou deleted in the dashboard in order to control them, but the regular users would only see that the comment was deleted without any pictures/username.

**Comment by hmkay** [comment]
Yes, that sounds good! Then I wrote that wrong in the acceptance criteria. I will make another story out of that? Or how should we proceed here, @fuzzylogic2000 and @mcastro-lqd ?

**Comment by fuzzylogic2000** [comment]
Well, it needs to be fixed in a4. @sabinammm already started a PR: https://github.com/liqd/adhocracy4/pull/905
Maybe someone has time to clean that up in the Christmas sprint (I think @Rineee wanted to work on the comment serializer..., but maybe someone else like me will also have some time to take care of some (a4) issues). So, keep it here as a reminder and we see if it is fixed when we do the next sprint? And otherwise either fix it then or think about where else to put it.

**Comment by hmkay** [comment]
Sounds great to me!
