### ISSUE TITLE
Empty message for report comment has no error message

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-kosmo#168]
**URL:** https://kosmo-dev.liqd.net/liqd/subjects/2021-00018/?comment=59
**user:** any authenticated follower
**expected behaviour:** If I want to report a comment and I want to send my report without a message, I expect to get an error or hint telling me that I need to add a message before sending the report.
**behaviour:** Report doesn't send, but no indication why
**important screensize:**
**device & browser:** 
**Comment/Question:** Is this even relevant or is this the behaviour as is expected?

Screenshot?
![image](https://user-images.githubusercontent.com/17978375/151782363-37abf62c-61ef-4e70-ad69-ded14e4a8629.png)

**Comment by phillimorland** [comment]
As we don't show that text anywhere i'm not sure if we will keep this user flow, @rilanari do you know?

**Comment by phillimorland** [comment]
As we are leaving it like this I will close this issue but open one in a4
