### ISSUE TITLE
#5763 Display 2 more categories of comments reported by AI

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#191]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**user:** *moderator*
**important screensize:** *Both*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8) & Chrome Version 99.0.4844.51*
**Comment/Question:** *Seems fine, I created 4 colours in case they want to differentiate them. They are #EBE8FF  #FCE5E5 #E7E7F1 #FCE5EC* 

![Screenshot 2022-04-19 at 10 01 49](https://user-images.githubusercontent.com/59610786/163957538-75f67674-cdd6-44c3-8d08-0e17f5680ae7.png)

**Comment by khamui** [comment]
Just to confirm, this is only about the coloring right @mcastro-lqd ? I am not following the title though..

**Comment by mcastro-lqd** [comment]
@khamui I normally try to put the title linking to the story, but its just about the colours
