### ISSUE TITLE
Profile Section + Organisations

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#193]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/rines-testproject/
**user:** *moderator*
**important screensize:** *Both*
**device & browser:** *Safari Version 15.3 (17612.4.9.1.8) & Chrome Version 99.0.4844.51*
**Comment/Question:** *Would it be possible to make the icon smaller here? In the design is 24 px and here they are 40 px. Also the titles could be 20pt instead of 24px. I think hierarchically it makes more sense to display the username bigger or the same size as the organisations. * 
<img width="360" alt="Screenshot 2022-04-19 at 10 18 44" src="https://user-images.githubusercontent.com/59610786/163958266-8cbedb0f-8044-462b-888d-8b098eb731fd.png">

**Comment by phillimorland** [comment]
fixed in https://github.com/liqd/a4-kosmo/pull/301
