### ISSUE TITLE
KOSMO | Blocking Mail Notification in German not correct

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#219]
**user:** *Participant*
**expected behaviour:** *The German version of the Mail should be consistent in the language and grammatically correct*
**behaviour:** *Parts of the mail is in German and parts are in English*

<img width="711" alt="Screenshot 2022-05-03 at 16 27 40" src="https://user-images.githubusercontent.com/77740788/166473780-1433adae-33c4-4893-8f5c-41a6908215af.png">

**Comment by Rineee** [comment]
fixed here https://github.com/liqd/a4-kosmo/pull/236
