### ISSUE TITLE
KOSMO | Highlighted through whole block of text

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#232]
**URL:** https://kosmo-dev.liqd.net/test-organisation/subjects/2021-00031/?comment=153
**user:** *moderator/ initiator/ participants/ visitors 
**expected behaviour:** Only highlighting where there are characters instead of whole text block
**Comment/Question:** this is just a question, but would it be lot of work to make the highlighting only where there are characters instead of the whole block. In the Zeplin design is what I mean. Do you think it would look a bit better?

In the design also there is a separation between lines, which makes it seem less heavy... What do you think?

Zeplin:
![Screenshot 2022-05-13 at 13 45 13](https://user-images.githubusercontent.com/77740788/168276763-c771f786-6fba-41c1-8725-178e662aaab5.png)

KOSMO:

![Screenshot 2022-05-13 at 13 35 56](https://user-images.githubusercontent.com/77740788/168276790-6809d96d-8965-46fa-9085-f631b2f656a2.png)

**Comment by phillimorland** [comment]
@rilanari I did try when doing the story but no luck, but just had a thought, will try it but if it doesn't work would be good to just have this as a nice to have as the elements used are great for accessibility but make it a little difficult for styling
