### ISSUE TITLE
Filter: Can we have "pending" as a default filter?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#239]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/debate-debate/
**user:** moderation
**expected behaviour:** I am shown only pending notifications
**behaviour:** Filter is set to "view all" as default

**Comment/Question:** Is this easy to set?

**Comment by Rineee** [comment]
@hmkay That is an easy fix, will add to milestone!
