### ISSUE TITLE
Capitalisation user dashboard

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#24]
**URL:** 
**user:** 
**expected behaviour:** Account Settings and User dahsboard should either both have a capitalized second word or both shouldn't. 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Screenshot from 2021-01-18 17-14-11](https://user-images.githubusercontent.com/8178179/104939447-b58d8900-59b0-11eb-9e6b-06ed6bc53a91.png)

**Comment by phillimorland** [comment]
in other platforms we use double capital so will do the same here
