### ISSUE TITLE
notification tiles: colours of category labels dont work for other languages than english

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-kosmo#245]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

The classes seem to depend on the translated category string and only work in english vesion:

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/169520664-e1697b2b-4769-47de-a7c4-5d18e43fbb9b.png)

![image](https://user-images.githubusercontent.com/9589411/169520759-984da6e1-672f-491f-98bf-fb654ad0c6c1.png)

**Comment by fuzzylogic2000** [comment]
There is too much magic happening for me here. @khamui When you fix this, can you maybe also mark in the scss file, that these comment badges are not used in the a4 comments, but in the moderator dashboard specific to kosmo? Or we move these classes elsewhere?
