### ISSUE TITLE
project tile in user dashboard might have different heights

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#25]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Screenshot from 2021-01-18 17-28-12](https://user-images.githubusercontent.com/8178179/104941134-f5557000-59b2-11eb-88f7-a58b17ed165d.png)

**Comment by phillimorland** [comment]
This i'll leave till after the carousels are in place as there's some confusion about which tiles

**Comment by fuzzylogic2000** [comment]
Cool!
