### ISSUE TITLE
#6011 Mailing blocked comment: Link in Mail should not link to parent comment

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#253]
**URL:** 
**user:** Participant
**expected behaviour:** the button "link to discussion" leads to general discussion
**behaviour:** Button links to concrete comment within the discussion and marks comment (that has nothing to do with origi al comment)
**important screensize:** desktop, mobile
**device & browser:** FF, MacOS

<img width="853" alt="Bildschirmfoto 2022-05-25 um 16 12 56" src="https://user-images.githubusercontent.com/30862422/170283367-81d2a217-055d-4715-80e4-24ef61cc6646.png">

**Comment by khamui** [comment]
Could not replicate this issue. I tried on dev in the exact same project (Debate debate). Link of Button I receive via E-Mail:
https://kosmo-dev.liqd.net/liqd/subjects/2021-00018/

@hmkay @fuzzylogic2000

**Comment by fuzzylogic2000** [comment]
Hmm, I think, I found it. Did you block the child of that comment? I guess you did block the comment that is also deleted now? https://kosmo-dev.liqd.net/liqd/subjects/2021-00018/?comment=100
So, nothing to do with it is not quite true.
But we need to find out, if that comment is a 
- comment on an idea, where we need to link to the idea.
- comment on a poll or document, where we need to link to the project page
- or a comment on a comment where we still need to link to the idea or project page of the parent comment.

**Comment by fuzzylogic2000** [comment]
Maybe it would be the easiest solution to actually just link to the blocked comment? Then it is also clear where in the discussion the blocked comment is.

**Comment by hmkay** [comment]
ah, it might be that it was a child comment! 
Anyhow, in the mail it says: "Zur Diskussion". So I think it should just go straight to the discussion and not to a specific place where the comment is/was. Otherwise it is confusing if you "land" on the middle of the page and do not know why.
