### ISSUE TITLE
KOSMO | Moderation Dashboard: Change the Word Statement to Feedback

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#261]
**URL:**https://kosmo-dev.liqd.net/userdashboard/moderation/detail/deliberation-on-how-to-use-ai-in-discussions/
**user:** *moderator/ 
**expected behaviour:** *Change the wording from Statement to Feedback to match the German Wording*
**Comment/Question:** *In the English version we use the term Moderation's Statement but we decided that Feedback would fit better. So it would be great to change wherever it is from Statement to Feedback* 
![Screenshot 2022-06-03 at 15 07 06](https://user-images.githubusercontent.com/77740788/171859987-63124575-b68f-405a-81ab-ca6f95268976.png)
![Screenshot 2022-06-03 at 14 59 18](https://user-images.githubusercontent.com/77740788/171859990-21807f8f-d0b8-45fd-a019-069a33a3f72f.png)

**Comment by khamui** [comment]
this is just about the actual english translation right? no need to change it in the code?

**Comment by khamui** [comment]
after confirmed with other devs we decided to only change the wording, not the code.
