### ISSUE TITLE
moderation dashboard: removed comments are shown with empty comment text

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-kosmo#269]
**URL:** 
**user:** 
**expected behaviour:** comments that have been removed are either marked as such (like in discussion) or not shown in moderation dashboard
**behaviour:** comments that have been removed by creator or moderation are shown with empty comment text, but no further note
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
@Rineee when you say removed that's deleted by the creator right? so should the notification in the mod dashboard then be deleted?

**Comment by Rineee** [comment]
> @Rineee when you say removed that's deleted by the creator right? so should the notification in the mod dashboard then be deleted?

Yes, both when the moderator or creator deleted the comment! I think we should in that case either
1. not show the notification in moderation dashboard (but then also statements are not show anymore and cant be edited)
2. show 'this comment was deleted by creator/moderation' like it is in the discussion

I'd say this is for @hmkay and @rilanari to decide!

**Comment by rilanari** [comment]
Hello @Rineee. I would go for option Nr 1. No need of showing any notification. Thanks!
