### ISSUE TITLE
adapt mobile view

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#271]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** Once folded, the organisations I am an initiator of only show when I click on the arrow
**important screensize:** mobile
**device & browser:** 
**Comment/Question:** see former issue: https://github.com/liqd/a4-kosmo/issues/60#issuecomment-770757256 

Screenshot?

**Comment by phillimorland** [comment]
@hmkay @rilanari i'm a little uncertain what you are after here, the issue you referenced requested a story be made for this problem and the explanation can be seen here: https://github.com/liqd/a4-kosmo/issues/60#issuecomment-767472459 
so is this a new issue which not to do with #60 and i'm just not getting it?

**Comment by phillimorland** [comment]
@rilanari @hmkay any thoughts on this? otherwise will take it out the milestone

**Comment by rilanari** [comment]
Hello @hmkay, I am also not very sure what is the issue as well... 
Do you think it is critical for the release? Thanks!

**Comment by hmkay** [comment]
Hello @phillimorland and @rilanari ,
This was an acceptance criteria that was written into one story. In the discussion of the story it was then said that I should put it into the issue list, link it to the former issue and put it into the milestone. 
Nevertheless - I am not emotionally connected to this issue. It was said that it should be checked/fixed if I remember correctly. But as it only affects initiators, maybe we can leave it out for now.

**Comment by hmkay** [comment]
So if you also do not remember, @phillimorland , maybe you could give it one last check and then we decide if we delete it?

**Comment by phillimorland** [comment]
@hmkay No I don't remember, can you link to the user story? the linked issue seems to be closed with the suggestion that you will write a user story: 
'@hmkay to make user story' 
so i'm now more confused?!

**Comment by hmkay** [comment]
We decided in this story that I should add the issue: https://taiga.liqd.net/project/mkay-kosmo/us/124
So we went into a loop here: issue --> story --> acceptance criteria --> issue. 

If I get it right, this is all about the organisations that are meant to be folded in mobile view, but are not folded. It would be good to have it fixed to have it done, but it is not critical. The issues we will not do anymore will be there if we transfer the moderations dashboard to aplus, though. But maybe that is fine?

**Comment by phillimorland** [comment]
@hmkay thanks for clarification! as mentioned in the linked issue this would be a lot of work, equivalent to a user story so I would not start it so late in the sprint so would close it here. 
Maybe @mcastro-lqd can say if we want to carry it over to a+ if we port this feature over? 

And as a point for the future, I think when writing issues with a complex history, as much context and links as possible would be really useful! Cheers!

**Comment by hmkay** [comment]
Yes, I totally agree with your point of adding as much context and links as possible would be helpful. I did understand my role as a solely executive one as I only got half of the complexity of the development. For next time, I will make sure to inform you earlier when everything is still fresh in order for you to check if it is understandable or leave it to one of you to write the issue ;P I totally understand that this issue is confusing and not helping to clarify what has been happening at all (also for me, btw).

**Comment by hmkay** [comment]
So if I got it right we still wait for @mcastro-lqd to decide if we carry this issue over to a+ ?

**Comment by phillimorland** [comment]
@hmkay only if we add the moderation dashboard to a+, I would think before we consider adding it to any other project we should have some thorough user testing and maybe we can reference this wherever we collect that data?
NOTE: this is about adding a cookie to remember if the organisation list is open or not when page is changed (tab changed)

**Comment by mcastro-lqd** [comment]
I just discussed with @phillimorland and we decided to label it as "nice to have" since we have no dev left for KOSMO, so it would be just in case we carry over to a+.
