### ISSUE TITLE
user dashboard's manual button does not fit the profile's box above

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#293]
**URL:** 
user's dashboard: https://kosmo-dev.liqd.net/userdashboard/overview/
project dashboard: https://kosmo-dev.liqd.net/liqd/dashboard/organisations/projects/
profile: https://kosmo-dev.liqd.net/profile/katharina/
**user:** 
**expected behaviour:** I think, we wanted to take the same button for the manual link in the user's dashboard as in the project dasboard. When we do that, the borders around the button and the user info box don't have the same colour. (see screenshot)
**behaviour:** The border for the user's info box is from styling from the profile view. So, the question is: which colour? Can we change the border-colour in the profile as well, so that it is the same everywhere? Because if we change it for the manual's button, it will be different from the left nav in the project dashboard.
**important screensize:**
**device & browser:** 
**Comment/Question:** Hope, that does make sense!

user's dashboard: 
![Screenshot from 2022-08-08 15-20-24](https://user-images.githubusercontent.com/8178179/183427824-449657de-df69-41fc-9ff0-8725aa4d061f.png)

project dashboard: 
![Screenshot from 2022-08-08 15-20-49](https://user-images.githubusercontent.com/8178179/183427859-95672754-8fac-49ed-bb23-880c5792019e.png)

profile: 
![Screenshot from 2022-08-08 15-22-21](https://user-images.githubusercontent.com/8178179/183428057-4cf05e25-78b4-4b4b-bd5e-39cd86166255.png)

@mcastro-lqd Please help and tell us what to do! (Very short form: can we also make the border in the user profile darker?)

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Yeah, I've always wanted to make the strokes less strong. But we can keep them dark then. I just updated on Zeplin too

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd We can also do it the other way round and change the borders to the lighter colour in the dahboard! (And wherever we use that button). If that's what you prefer. It will be more for you to test afterwards, though. :)

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 yes, Im afraid of breaking everything later

**Comment by fuzzylogic2000** [comment]
Decision: make the profile border darker, but in a+!

**Comment by fuzzylogic2000** [comment]
Well, the user profile does look different in a+..., so have to fix here
