### ISSUE TITLE
fallback user images look weird in debate's topic list

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#299]
**URL:** https://kosmo-dev.liqd.net/liqd/projects/debate-debate/
**expected behaviour:** user images have filled background
**behaviour:** User images do not seem to have a filled background 

[link to image](https://kosmo-dev.liqd.net/static/images/avatar-02.7896f6b26396.svg)

@mcastro-lqd would you be able to give us new images? these are the ones we have: https://github.com/liqd/a4-kosmo/tree/main/adhocracy-plus/assets/images/avatars

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @phillimorland I just added them to the folder solid here Nextcloud/Projekte/KOSMO/Kreation/210413-avatar/210413-avatar-svg

**Comment by phillimorland** [comment]
fixed in https://github.com/liqd/a4-kosmo/pull/301
