### ISSUE TITLE
wording on button to information page in user dashboard

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-kosmo#304]
**URL:** 
**user:** 
**expected behaviour:** the wording on the button complies with the page it links to
**behaviour:** it says manual
**important screensize:**
**device & browser:** 
**Comment/Question:** 
We initially wanted to link to the manual wiki, that is why in the designs it says 'Manual' on the button. However, we now want to link to a wagtail page with (as far as I know) platform information/getting started information on it. So, we should adjust the wording, but to what? 
Screenshot?
![image](https://user-images.githubusercontent.com/9589411/184142937-2e45fc07-d4b8-4e39-962a-c5d4d80a73e1.png)

**Comment by Rineee** [comment]
@rilanari @hmkay @fuzzylogic2000 Here is the issue, lets discuss about the wording! I guess it depends on the content of the page it links to :) Something like 'getting started' or 'more information'?

**Comment by rilanari** [comment]
Thanks @fuzzylogic2000 I was thinking 'learn more' (?)
or maybe @mcastro-lqd can give us a hint?

**Comment by fuzzylogic2000** [comment]
No, it should be thanks @Rineee ! :smile: 
I also like "getting started". "learn more" is quite unspecific because there's nothing it refers to, like more of what?

**Comment by mcastro-lqd** [comment]
@rilanari I thought the content would be just the participant part of the Wiki, but when we had the idea of the Wagtail page I used Getting Started too, so Im fine with both.

**Comment by rilanari** [comment]
'Getting Started' I like!! :)

**Comment by Rineee** [comment]
Cool, I will change it to that then!
