### ISSUE TITLE
#3709 and #3680 [KOSMO] Setting up User Dashboard & adapt styling of tile of user profile

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#31]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**important screensize:** *Both*
**device & browser:** *Safari Version 14.0.2 (16610.3.7.1.9)*
**Comment/Question:** *I added only 2 comments in the pdf file, I guess the Mobile version wasn't implemented yet, so I'll just leave the screenshot here without any comments. Thanks in advance* 

[200121-d-user-dashboard.pdf](https://github.com/liqd/a4-kosmo/files/5835312/200121-d-user-dashboard.pdf)

![IMG_6749 (1)](https://user-images.githubusercontent.com/59610786/105022860-84fa2d80-5a4a-11eb-8d50-dfedcfb7871d.PNG)

**Comment by phillimorland** [comment]
@mcastro-lqd yeah, mobile we are behind on, doing it now, sorry!
