### ISSUE TITLE
Overview Adjustments 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#311]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** *all*
**important screensize:** *Both*
**device & browser:** *Safari Version 15.6 (17613.3.9.1.5)*
**Comment/Question:** *Since most of the stuff are styling I'll add more than one thing here, let me know if it should be each item separated so I can split.* 

01 – Organisation Size and No-picture Icon: These sizes are a bit too big, I would make them 32 px. Would it be possible to change the default empty one to something like that? We can use this one from FontAwesome, but the sketch plugin is never updated. https://fontawesome.com/icons/house-user?s=solid
<img width="87" alt="Screenshot 2022-08-16 at 11 39 48" src="https://user-images.githubusercontent.com/59610786/184849182-ad5766d7-bdad-4b05-8204-be7f31013739.png">

02 – Manual Button: They should be closer to the Profile Tile than to the organisations. Around 16 px is fine, currently is 48px
<img width="337" alt="Screenshot 2022-08-16 at 11 44 59" src="https://user-images.githubusercontent.com/59610786/184849714-8da4cfde-7676-4d81-a5ec-b450b74726fb.png">

03 – Titles: I know the changes were a bit chaotic here, but since we changed the old aplus font to the new KOSMO CI one, I guess just replacing the old one with the new one may have left everything too big, I would do Main Titles using 20pt (Following, Activities, Projects) and Secondary Titles/Buttons 16pt (Overview, Moderation, Initiator Organisations + Organisations). 

04 – Org Dropdown: This is still off on Mobile, If its hard to fix it I would leave them without the expand/collapse option.

**Comment by phillimorland** [comment]
fixed with https://github.com/liqd/a4-kosmo/pull/316
