### ISSUE TITLE
Organisations Names not shown

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#314]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** Initiator
**expected behaviour:** Show the name of the organisations
**behaviour:** In the organisations list, there are two organisations whose names are not shown.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
![Screenshot 2022-08-16 at 12 11 02](https://user-images.githubusercontent.com/77740788/184855287-9e20a65e-f374-4dff-8a16-65b6b3e6d8fd.png)

**Comment by phillimorland** [comment]
@rilanari I changed the organisation name to the title as the name is assigned in the django admin and is like the url, the title is assigned in the organisation settings is normally more similar to the name the organisation uses and is more human readable. Have you set the name in your org settings?
