### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#325]
**URL:** Tile Component in the Following section on Users Dashboard
**important screensize:** *Desktop*
**Comment/Question:** *The progress bar is out of the tile when the text is too long* 
<img width="339" alt="Screenshot 2022-08-31 at 10 20 50" src="https://user-images.githubusercontent.com/59610786/187631019-14a44f67-0b28-4df6-94a0-5e6129a33226.png">

**Comment by phillimorland** [comment]
NOTE: a+ issue

**Comment by philli-m** [comment]
should be fixed with rebase but no link so can't check
