### ISSUE TITLE
Default Project missing in Stage

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#326]
**URL:** https://kosmo-stage.liqd.net/team-kosmo/projects/landesweiter-beteiligunshaushalt/
**user:** *participants/ 
**expected behaviour:** Participants do not follow a default Project
**behaviour:** *Describe the issue*
**important screensize:** All
**device & browser:** All
**Comment/Question:** Hello devs, I noticed that there is no project in Stage set as default to follow. Should I make one and you will set as default? Thanks
![Screenshot 2022-09-02 at 15 26 45](https://user-images.githubusercontent.com/77740788/188157134-e451ee1b-c48f-4657-8dba-41189668462d.png)

**Comment by rilanari** [comment]
Here are two projects that can be used as default

**Comment by Rineee** [comment]
Hello @rilanari, you can set the default project yourself! In wagtail you neet to go to settings -> platform settings and there you find the field 'sample project slug', where you can enter the slug of the project. The slug is the last bit of the url of the project page, e.g. for 'Debatte über KOSMO' it would be 'erste-projekt-auf-kosmo'. Let me know if it worked! :)

**Comment by rilanari** [comment]
Hallo Katharina, it seems to be working now! Thanks!
