### ISSUE TITLE
Incoherence of naming categories in filter and as tags

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#331]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/debate-debate/ (moderation dashboard)
**user:** moderator
**expected behaviour:** the filter uses the same words as the tags are for for the categorisation of the AI 
**behaviour:** the filter uses different words than the tags (see screenshot)
**important screensize:** desktop
**Comment/Question:** The right categorisations are the one from the tags, right @rilanari ?

![Bildschirmfoto 2022-10-20 um 11 46 26](https://user-images.githubusercontent.com/30862422/196916090-45e2cbc8-688f-49e9-821c-8aa9e2b3fc22.png)

**Comment by rilanari** [comment]
Right! the right one should be Schädlich in both! Thanks for checking @hmkay !

**Comment by Rineee** [comment]
This is a translation issue. So it should be Schädlich and Konstruktiv (instead of Hochwertig) in the filter also, right?

**Comment by hmkay** [comment]
Yes, @Rineee !
