### ISSUE TITLE
[KOSMO] No Welcome Mail sent by Sendinblue

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#335]
**URL:** https://kosmo.liqd.net/ - https://kosmo-stage.liqd.net/ - https://kosmo-dev.liqd.net/
**user:** New User
**expected behaviour:** As a new user I would expect to receive a welcome mail from Sendinble 
**behaviour:** I receive no welcome mail
**important screensize:** none
**device & browser:** web browsers
**Comment/Question:** When I tested the user story with stage it worked. But now its not. Would it be something that has been wrongly activated in Sendinblue? 

Screenshot?

**Comment by Rineee** [comment]
> @rilanari I just checked on dev and that works!

And prod does too!

**Comment by Rineee** [comment]
> > @rilanari I just checked on dev and that works!
> 
> And prod does too!

And stage does too!

Sometimes they can be sent with delay, but you can check in sendinblue if the e-mails got sent already!
