### ISSUE TITLE
project in moderation tab not shown

### ISSUE THREAD

**Issue by lthueer** [liqd/a4-kosmo#344]
**URL:** https://kosmo-stage.liqd.net/userdashboard/moderation/
https://kosmo-stage.liqd.net/testorga-luca/
**user:** admin, moderator
**expected behaviour:** project is shown
**behaviour:** project not shown
**important screensize:**
**device & browse
**Comment/Question:** 

- tested for brainstorming + debate
- project should be shown in moderation tab when project is created (by admin, initiator) and when moderators are added to proejct
- also not when a comment is reported within the project

![Bildschirm­foto 2023-03-02 um 11 53 13](https://user-images.githubusercontent.com/36957474/222408690-b2ce9675-6384-4935-8684-8fd5c1166622.png)

**Comment by fuzzylogic2000** [comment]
Was fixed by @philli-m yesterday.
