### ISSUE TITLE
[KOSMO] wrong message in discussion when blocked comment

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#346]
**URL:** https://kosmo-stage.liqd.net/userdashboard/moderation/detail/schutz-vor-waldbranden/
**user:** all
**expected behaviour:** according to user story  #4922 (https://taiga.liqd.net/project/liqd-liquid-software/us/4922) the message shown in the discussion should be “this comment was blocked by moderation" 
**behaviour:** the message now is "unbekannter Nutzer"  
**important screensize:** all
**device & browser:** all
**Comment/Question:** 

<img width="877" alt="Screenshot 2023-03-03 at 10 14 30" src="https://user-images.githubusercontent.com/77740788/222684594-f2481fdb-84f2-4d1d-a491-71cc72cb9ea9.png">

**Comment by Rineee** [comment]
It is super weird, I tested with a blocked comment in aplus and there the message shows correctly. Also, when I update a4 to newest version, it works in kosmo, but only when I unblock and then block again the comment. For previously blocked comments, it still does not show the message. This makes no sense to me :woman_shrugging:
