### ISSUE TITLE
KOSMO | Spacing issue in the Moderation Dashboard

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#350]
**URL:** https://kosmo-stage.liqd.net/userdashboard/moderation/detail/defakts/
**user:** Moderator
**expected behaviour:** there should be a space between the user names and the report message (see attached image)
**behaviour:** 
**important screensize:** 
**device & browser:** all
**Comment/Question:** 

![Screenshot 2023-04-18 at 14 31 20](https://user-images.githubusercontent.com/77740788/232791634-0a7c6d19-e13d-4f58-b748-cb8441d23fe5.png)

**Comment by philli-m** [comment]
fixed
