### ISSUE TITLE
Comments are too slow to be posted when press the submit button

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#354]
**URL:** https://kosmo-dev.liqd.net/test-organisation/projects/poll-for-more-deliberation/
**user:** participant
**expected behaviour:** when the participant write a comment and press post, the comment is posted quickly
**behaviour:** the "post" button does not work enough and sometimes it results in posting the comment several times due pressing the button repeatedly. 
**important screensize:** desktop  (
**device & browser:**  Desktop, firefox 110.0 (64-Bit)

![Screenshot 2023-06-21 at 14 40 43](https://github.com/liqd/a4-kosmo/assets/77740788/fe4e81c8-5c8c-4f69-bcdf-03f0f396660d)

**Comment by philli-m** [comment]
@rilanari nice catch, this seems to be a long standing issue which is also present in a+ and probably mB as it comes from comments in a4 so we won't fix it for this release but have created an issue in a4 and will prioritise it so will be fixed with the next rebase and release

**Comment by philli-m** [comment]
closing in favour of https://github.com/liqd/adhocracy4/issues/1428
