### ISSUE TITLE
line break in user tile

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#39]
**URL:** 
**user:** admin
**expected behaviour:** Name stay the same
**behaviour:** name breaks within the word
**important screensize:** desktop and mobile
**device & browser:** firefox 84.02 on macOS Big Sur
**Comment/Question:** Here the line is breaking, is it possible to have longer names displayed in 2 rows? Thanks!

<img width="262" alt="Bildschirmfoto 2021-01-20 um 17 29 36" src="https://user-images.githubusercontent.com/30862422/105205758-dfc47f80-5b45-11eb-9b71-879e3a78cef5.png">

**Comment by phillimorland** [comment]
@hmkay this is actually inherited from a+, should it stay here or should it be in a+, i'm a little confused about that?

**Comment by hmkay** [comment]
haha, ok :D 
Yes, eventually it all should go to a+, so maybe we could make it nice and neat here and then at some point in March/April port it over!
