### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#40]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** admin
**expected behaviour:** description underneath my profile appear in my set language
**behaviour:** description appears in English

**Comment/Question:** Do you need a translation for that? Have we already decided on a set description? 

<img width="262" alt="Bildschirmfoto 2021-01-20 um 17 29 36" src="https://user-images.githubusercontent.com/30862422/105206094-40ec5300-5b46-11eb-8c0b-970be888a1af.png">

**Comment by fuzzylogic2000** [comment]
Do we want to translate it here or do we want to port it to a+ anyway and then translate in transifex? How important is it that it is translated before it is ported to a+?

**Comment by hmkay** [comment]
Uh! Yes, transifex would be better! Let´s do that - it is not that important to translate it before being ported to a+. We do need to port it then to a+ in march/april I guess!

**Comment by fuzzylogic2000** [comment]
All prepared for kosmo-specific translations. Will be closed with them
