### ISSUE TITLE
get sorting of projects right and be consistent with indication on project tile

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-kosmo#41]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** see https://github.com/liqd/adhocracy-plus/issues/1074 and https://github.com/liqd/adhocracy-plus/issues/1076
It here also applies to project list in user dashboard.

Screenshot?

**Comment by phillimorland** [comment]
@Rineee is this now fixed in a+?

**Comment by Rineee** [comment]
> @Rineee is this now fixed in a+?

No, it is not. I will try start a discussion there or maybe we would even need a meeting for it, because it is kind of concepting.. what do you think @fuzzylogic2000?

**Comment by rilanari** [comment]
Hello @Rineee, I see that the issues in a+ have been closed, can I close this one as well? 

Thanks

**Comment by Rineee** [comment]
@rilanari The issue is closed in a+, because there is a story for that now, but we have not yet been working on it.. but if you are happy with the project sorting in the carousel in the user dashboard, we can close this issue (it is currently sorted active, future, past projects) and then eventually get the changes from aplus.

**Comment by rilanari** [comment]
perfect I will close the issue then, and see if we will implement the changes from a+! 
Thanks
