### ISSUE TITLE
Naming of user Dashboard: My profile / Mein Profil

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#46]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/

There is a name now! It will be "My profile" / "Mein Profil"

We will need to talk about the implications though, I totally see that we need to get some consistency in the names...so comments and things we need to keep in mind are more than welcomed! =)

Thanks!

**Comment by phillimorland** [comment]
@hmkay we already have a profile page that is publically visible, also the implication of profile is that it can be viewed by others, at least thats how many other sites use it, faceboomk, twitter, ect. (sorry!)
My profile:
https://kosmo-dev.liqd.net/profile/PhilliAdmin/

**Comment by hmkay** [comment]
@phillimorland I get your point...I also just checked facebook after AGES and apart from being shocked by it I do have another suggestion:

DE: Meine Übersicht
ENG: Home

Is it also easy to include icons? Than we could use the all-known-home-button. And also adapt the settings with that (That would be another feature request?)

**Comment by hmkay** [comment]
Ah, also wanting to ask @mcastro-lqd what he thinks about it!

**Comment by hmkay** [comment]
And we now would have three things:

profile (public)
home (private)
settings (private)

**Comment by phillimorland** [comment]
@hmkay is that the final wording? we don't need the german as that will all be done in transifix

**Comment by mcastro-lqd** [comment]
@hmkay As Philli mentioned, I think Profile should be used in public profiles and I still prefer Overview than Home, cause Home to me sounds more like the current https://adhocracy.plus page. But Im fine with both.

**Comment by phillimorland** [comment]
Overview is more descriptive and we do already use home, the icon for the organisation home pages
