### ISSUE TITLE
User dashboard doesnt show three tabs

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#47]
In the acceptance criteria of the user story https://taiga.liqd.net/project/liqd-liquid-software/us/3680?milestone=245 are written three tabs. There are only 2 shown, but I guess this is easily adaptable and can be chanegd as soon as we actually need them, did I get that right?

Thanks!

**Comment by phillimorland** [comment]
@hmkay yep it is easy to add an extra, and the mobile styling will be fine as it's a dropdown. As we discussed not implementing the 3rd tab in this iteration it was left out.
