### ISSUE TITLE
User Dashboard: Mobile doesn´t show profile tile

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#48]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** participant
**expected behaviour:** I can see the profile tile
**behaviour:** I can only see the tab
**important screensize:** mobile
**device & browser:**  Iphone, Safari
**Comment/Question:** It also happens when I make the screen smaller on firefox (is that valid information you can actually process? If not, let me know :D )
![IMG_B09C801876B6-1](https://user-images.githubusercontent.com/30862422/105700782-a6a35b00-5f09-11eb-8a87-3aee67317265.jpeg)

**Comment by phillimorland** [comment]
@hmkay can't reproduce on any of my devices, can you try clearing your cache or checking on a private browser? if still a problem then maybe we can do a call

**Comment by hmkay** [comment]
I checked on a private browser and it worked! Thanks!
