### ISSUE TITLE
User Dashboard: Wording if no projects are being shown

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#49]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** admin

There is a typo in the German wording: It should be "Diese"

If possible, could you then adapt it to:
DE: "Sie sind bislang noch in keinem Projekt aktiv."
ENG: "You are not active in any projects yet." (@phillimorland is that right?)

<img width="485" alt="Bildschirmfoto 2021-01-25 um 12 35 52" src="https://user-images.githubusercontent.com/30862422/105701649-e3bc1d00-5f0a-11eb-9ec3-b4c6702108e3.png">

**Comment by hmkay** [comment]
Perfect, thanks! Do I do that for KOSMO or for aplus? What makes more sense?

**Comment by phillimorland** [comment]
on transifix do it for a+, we'll port over, get the translations from transifix and port them back
