### ISSUE TITLE
User Dashboard: Infos from moderations if not being moderations

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#52]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** moderator

**expected behaviour:** If I am a moderator but if then the initiator takes away my moderations rights, I shouldn´t be able to see the projects or the organisation if I haven´t done any action/activity.

**behaviour:** organisation and projects are shown

**Comment/Question:** I know these are many if´s, but this could be the case if an initiator adds a moderator by accident and then takes away the rights again.

<img width="1096" alt="Bildschirmfoto 2021-01-25 um 13 05 26" src="https://user-images.githubusercontent.com/30862422/105703786-0bf94b00-5f0e-11eb-9566-56040b125047.png">

**Comment by fuzzylogic2000** [comment]
No, the projects are still shown, because you follow them. even though this is autofollow, we shouldn't autounfollow. So, the moderator can still see the project, but is still not allowed to moderate it anymore.

**Comment by hmkay** [comment]
aaaah, cool! Ok, thanks!
