### ISSUE TITLE
User Dashboard: What to include into activities?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#54]
This is a list of what we are counting in the activities of the user dashboard and the profile. Maybe you also know more about that? What kind of activity is counted and do we think this is how it should be?

Not counted as activity: 
- participating in poll
- participating in interactive event
- liking
- setting up a project

**Comment by phillimorland** [comment]
these are all anonymous activities, maybe we can add them in the userdashboard but not in the public profile? not sure how hard that is though?

**Comment by fuzzylogic2000** [comment]
The things that are counted are configured here: https://github.com/liqd/a4-kosmo/blob/master/apps/actions/apps.py
If we want to add more, we can do that.
And to add them only in one place, we would filter the ones, we don't want to have out of the list.

**Comment by phillimorland** [comment]
for private overview it would be good to have all activities including private actions (polls) 
@hmkay to make a user story
