### ISSUE TITLE
Profile: "Show more" if profile follows more than 9 projects?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#55]
**URL:** https://kosmo-dev.liqd.net/profile/Marie-Kathrin%20Siemer/
**user:** any

**Comment/Question:** Should users be able to see ALL projects that the profile is following? Currently, it is max. 9. Is this important?

**Comment by phillimorland** [comment]
I would say not right now. I think the only way to actually answer this would be user testing and as public profile isn't the focus of this project, I say we leave it, it allows our users more privacy and following more than 9 active projects might be considered an edge case

**Comment by hmkay** [comment]
Cool! Thanks!
