### ISSUE TITLE
User Dashboard Initiator Mobile: Organisations are always again shown

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#60]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** initiator
**expected behaviour:** If I minimise "Initiator Organisations" and "Organisationen", I would like them to stay minimalised
**behaviour:** They are again "ausgeklappt, as soon as I do something on the page.
**important screensize:** mobile
**device & browser:** Iphone, Safari, private mode
**Comment/Question:** I know this is confusing because the other issue from the perspective of a participant is not showing any organisation....?!? 

![IMG_A618E5C3479A-1](https://user-images.githubusercontent.com/30862422/105745211-52ff3480-5f3e-11eb-93ed-e2b48fb28815.jpeg)

**Comment by phillimorland** [comment]
@hmkay what does "I do something on the page." mean? when i click and leave the page and return then everything is open again which is normal?!

**Comment by fuzzylogic2000** [comment]
I guess it means going to another "tab"? The problem is, that we didn't really use tabs, but only made it look like that. Remembering if someone closed the organisations would require js and a cookie, so would be quite an enhancement, that goes over the story, I would say.

**Comment by phillimorland** [comment]
@hmkay to make user story

**Comment by hmkay** [comment]
xD I just DO something. That seems to be cristal clear! 

...

sorry. And thanks ;)
