### ISSUE TITLE
User Dashboard: 404 error

### ISSUE THREAD

**Issue by rilanari** [liqd/a4-kosmo#63]
**URL:** https://kosmo-dev.liqd.net/userdashboard/
**user:** participant / initiator
**expected behaviour:** I would expect to go to the same site than https://kosmo-dev.liqd.net/userdashboard/overview
**behaviour:** 404 Error
**important screensize:**
**device & browser:** Firefox
**Comment/Question:** when I go to userdashboard/overview it is ok! I am  not sure if that is ok!

Screenshot?
![Screenshot 2021-01-26 at 13 59 50](https://user-images.githubusercontent.com/77740788/105849129-44695980-5fe0-11eb-8e7f-20facd447f9b.png)

**Comment by Rineee** [comment]
This is fine, the url https://kosmo-dev.liqd.net/userdashboard/ doesnt exist. For example the same if you go to https://kosmo-dev.liqd.net/profile, it doesnt exist, but https://kosmo-dev.liqd.net/profile/RineUser/ does.

**Comment by Rineee** [comment]
You didnt get there by some link, but entered it manually, right? @rilanari
