### ISSUE TITLE
Wagtail questions: Naming "organisation" and where to find adress

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#69]
**URL:** https://kosmo-dev.liqd.net/admin/settings/a4_candy_cms_settings/organisationsettings/2/
**user:** admin

**Comment/Question:** Whoop whoop, thank you so much for the adaptation of the platform name! I have only questions:

- Where are "adress" and "contacts" of the organisation shown? 
- I also found the naming "organisation settings" a little confusing, as we also have the organisation dashboard with the projects - but this would be even one level higher. I think we should make the differences clear - maybe by claiming them "platform settings"? What do you think?
 
<img width="718" alt="Bildschirmfoto 2021-02-01 um 12 30 11" src="https://user-images.githubusercontent.com/30862422/106453562-cd254100-6489-11eb-8765-4c7f219a2ad9.png">

**Comment by fuzzylogic2000** [comment]
The other two fields (address and contact) were already there. We just added another one. I think they are in the contact form, when you add one?!
Yes, we can rename them to platform settings (but @devs maybe only in the frontend, so we don't need to change it in all the templates ...?!)

**Comment by fuzzylogic2000** [comment]
Right, maybe we can also add helptexts, where these appear. But wording for these would be great!
Maybe @fredewe can help as he knows, where the other fields appear as well. :)

**Comment by phillimorland** [comment]
I also was confused by that naming but I agree that we shouldn't change them in the code, so frontend sounds good, for the helptext can we just add:
'to be displayed on contact form'

**Comment by hmkay** [comment]
sounds good! Could we also add a help text for the platform name? Such as "to be displayed in the disclaimer (how is the bottom called?), in the tab,..."

**Comment by fredewe** [comment]
It is shown in the contact page:
![Bildschirmfoto 2021-02-01 um 15 42 33](https://user-images.githubusercontent.com/5470479/106474046-c952e800-64a4-11eb-856d-e1402bbc029b.png)

**Comment by fuzzylogic2000** [comment]
Alright, @hmkay ! Could you give us the final wording for all fields and helptexts, please?

**Comment by hmkay** [comment]
@fuzzylogic2000 Yes!! Could you only check if this makes sense and if I got the right technical descriptions?

Platform name
*This name appears in the footer of all pages as well as in the tab of the browser.*

Address
*The address is published on the contact form.*

Contacts
*The contacts are published on the contact form.*

**Comment by hmkay** [comment]
Oh and the "organisation settings" would change into "Platform settings" (only frontend)

**Comment by fredewe** [comment]
The platform name appears also in the mailings, right?

**Comment by hmkay** [comment]
You are right, thanks! Thus it should be:

Organisation Settings --> Platform settings

Platform name
*This name appears in the footer of all pages and e-mails as well as in the tab of the browser.*

Address
*The address is published on the contact form.*

Contacts
*The contacts are published on the contact form.*


I think with this it should be fine, it should give enough information on the how what when questions.
