### ISSUE TITLE
Alert for following/unfollowing only mentions emails

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#70]
**URL:** 
**user:** 
**expected behaviour:** I want to also be informed that I can see the projects I am following in my overview (and maybe also that everyone can see them in my profile
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** @hmkay Here I use an issue to point out sth. that should/might become a story. :stuck_out_tongue_winking_eye: Seemed the easiest way to keep track of it?!

Screenshot?
![Screenshot from 2021-02-02 17-00-20](https://user-images.githubusercontent.com/8178179/106627020-a09c2280-6578-11eb-8353-18ca7ee97e13.png)
![Screenshot from 2021-02-02 17-01-07](https://user-images.githubusercontent.com/8178179/106627021-a134b900-6578-11eb-8b81-1271b56e8893.png)

**Comment by hmkay** [comment]
@fuzzylogic2000 really nice hint, thanks!! I will add it to the Taiga!

**Comment by hmkay** [comment]
noted down in Taiga as acceptance criteria of US #71 in KOSMO Backlog
