### ISSUE TITLE
user dashboard: inconsistencies in which followed projects are shown?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#71]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** any
**expected behaviour:** I can always access and see the projects, I am following
**behaviour:** We decided about different rules that do not go all well together. See below
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Rules we decided on:
- There are only active projects (current ones and upcoming) shown in the carousel. The most projects shown are 5.
- The link to all projects is only shown, if there are projects in the carousel.

Because of that, it can happen, that there are no projects in the carousel, and the link is not there, because the user only follows finished projects.
For now, I would propose to also show the finished ones in the carousel.

**Comment by fuzzylogic2000** [comment]
@hmkay @rilanari I think we need some action and decision here. This means that if I only follow finished projects, they do not show up in the overview and I also cannot access them.

**Comment by rilanari** [comment]
@fuzzylogic2000 
i think I am a bit confused here... shouldn't the overview for moderators the same as for participants? 
are finished projects shown in overview for participants? 
moderators can access to finished projects also in Moderators Tab, right? 

my suggestion would be that the overview for Moderators follow the same logic than for Participants...

**Comment by fuzzylogic2000** [comment]
It's not for the moderators but about the overview for eveyone. When you are logged in and follow the link in the issue, you should see. You can unfollow all active and future projects, then you have an empty list, even if you still follow past projects.
@rilanari

**Comment by hmkay** [comment]
@fuzzylogic2000 Thanks for your thoughts! I think your suggestion is good! You are totally right - we do need to display the finished projects as they might contain important information after the participation (results, e.g.).

So do it, also show the finished ones!
