### ISSUE TITLE
UX/UI testing story https://taiga.liqd.net/project/liqd-liquid-software/us/3711

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#72]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** *moderator/ initiator*
**important screensize:** *Both*
**device & browser:** *Safari Version 14.0.2 (16610.3.7.1.9)*

Desktop: 
[200211-d-3711-overview-of-users-dashboard.pdf](https://github.com/liqd/a4-kosmo/files/5964081/200211-d-3711-overview-of-users-dashboard.pdf)

Mobile:
[200211-m-3711-overview-of-users-dashboard.pdf](https://github.com/liqd/a4-kosmo/files/5964084/200211-m-3711-overview-of-users-dashboard.pdf)

**Comment by phillimorland** [comment]
@mcastro-lqd thanks for these! I have some clarifying texts below also when looking through the designs I got a little confused about which ones, is there anyway to makr the final design on zeplin? maybe they can all have like a final tag on them? 
Desktop
5. I wasn't sure which design you were referring to about the current tiles? 

Mobile:
4. I cannot replicate this issue. Can I ask just to confirm, there is a list of organisations when viewing on desktop and when that list turns into a dropdown on mobile you cannot see any organisations even after opening and closing the dropdown?
6. style mobile arrows with zeplin design (check left cropping)
8. change tiles on view more screen? which desktop design? this referes to desktop number 5 i think, i could only find a comment here but nothing else although some of the design looked really old so I don't really want to be trying to copy anything thats not right https://app.zeplin.io/project/5fe363c415be15a48946ca29/screen/5fe369b5adeaaeacadb14449

**Comment by mcastro-lqd** [comment]
@phillimorland Sorry, I missed these comments

Here you go:

5. Like the Profile one: 
<img width="1401" alt="Screenshot 2021-04-13 at 12 17 06" src="https://user-images.githubusercontent.com/59610786/114537162-2bbd2700-9c52-11eb-9f65-c3f6c27ad41b.png">

4. Yes, I just tested it again but I still can't see them. (Tested on Safari)
![IMG_9568](https://user-images.githubusercontent.com/59610786/114537691-cd447880-9c52-11eb-917f-d27c641d6438.jpg)

6. I just thought about making these cropped tiles that already gives the user the impression of a slidable gallery. Like these examples: 
![IMG_9570](https://user-images.githubusercontent.com/59610786/114538420-acc8ee00-9c53-11eb-9128-325b62be9668.jpg)
![IMG_9569](https://user-images.githubusercontent.com/59610786/114538432-ae92b180-9c53-11eb-93dd-c1a90f2b755d.jpg)

But as mentioned, if its too hard, we can stick to the current arrows, as long as they don't show when there is nothing else to be seen in both sides. (Eg. Currently there is an arrow on the left but no project to be seen if you slide to the left) 

8. Yes, it was the same as the Desktop 5 point. I just thought these tiles would be like the current ones on Profile: 
eg. https://aplus-dev.liqd.net/profile/m.castro/
