### ISSUE TITLE
Mailings on stage?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#87]
**URL:** https://kosmo-stage.liqd.net/
**user:** moderation / participant
**expected behaviour:** From Liquid, I receive E-Mails if I register or invite myself to moderate
**behaviour:** I didn´t receive any mail which asked me to confirm the mdoeration

**Comment/Question:** Did we decide to do so? Or is this a bug?

**Comment by fuzzylogic2000** [comment]
Like on the other dev and stage platforms, you should get emails to liqd.net addressee, but not to others.
Does it work on dev like you would it expect it to?

**Comment by hmkay** [comment]
Yes, exactly! 
So, I testes dev and if I add myself to the moderation team, I do not get an e-mail. I do get an e-mail if I report a comment. I can also register and I also get a mail. I just don´t get a mail if invited for moderation. Does that help as an explanation? I am not sure if I made myself clear ;)


<img width="659" alt="Bildschirmfoto 2021-04-06 um 15 27 06" src="https://user-images.githubusercontent.com/30862422/113718062-91f2f880-96ec-11eb-9686-e570731fca6c.png">

**Comment by Rineee** [comment]
@hmkay I just checked it and I receive the e-mail. I think you might try again with m.siemer@liqd.net instead of m.siemer@liqd.de? :stuck_out_tongue:

**Comment by fuzzylogic2000** [comment]
@hmkay Did you try with your liqd.net address? Can we close it?

**Comment by hmkay** [comment]
@fuzzylogic2000 @Rineee I feel so embarrased xD And yet so glad that I added a screen shot. Thanks for your check! I tested again and everythings fine!

https://media.giphy.com/media/BxWTWalKTUAdq/giphy.mp4
