### ISSUE TITLE
AI classification: Why is there a field for comments?

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#88]
**URL:** https://kosmo-dev.liqd.net/django-admin/a4_candy_classifications/aiclassification/1/change/
**user:** admin

I have to fill in a comment regarding the classification. I do not understand that - what should I fill in? And is this necessary? Or might it even hinder the AI? Does the AI have to fill in something there? 

So many questions... ;)

<img width="794" alt="Bildschirmfoto 2021-04-06 um 16 42 19" src="https://user-images.githubusercontent.com/30862422/113729198-1480b580-96f7-11eb-9c6e-a0fdcb656783.png">

**Comment by Rineee** [comment]
@hmkay Sorry, we should have explained that before..The comment is a reference to the actual comment object stored in the database, so it changes every time the comment is updated. Now consider the case that the comment is changed after the classification has been stored and before the moderator sees it. He would then see a different text than the one that has been classified. This is what we need 'comment text' for, it saves the text of the comment at the moment the classification is stored. You could try that out by saving a classification with the text of the comment (as you did above) and then change the text of the comment it refers to and look at the classification again. The comment should have changed, but comment text remains the same.

**Comment by hmkay** [comment]
Hey @Rineee ,

Thank you so much for the explanation - and thanks for thinking about that situation! It totally makes sense. I now tried to test it, but for some reason the reported comments do not show in the "user classifications" anymore. Dunno if you are currently working on that?

**Comment by Rineee** [comment]
@hmkay What exactly do you mean? I just tested it - reported a comment and then there is a new user classification object in the admin. That doesnt work for you?

**Comment by Rineee** [comment]
More explanation, because we actually changed that after you last tested I just realized: now every time a comment is reported (only comments, not ideas etc..), a user classification object with classification 'offensive' is created (additionally to the report). You could then edit the reported comment -> comment object of classification changes, but comment text remains the same.

**Comment by hmkay** [comment]
Awesome, thanks for the explanation, @Rineee ! I really checked with ideas, that does not work - but comments are fine for now! So thanks!
